;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(autopair-insert-opening
                               js2-beginning-of-line
                               yas-expand
                               js2-end-of-line
                               autopair-insert-or-skip-quote
                               upcase-region
                               c-electric-delete-forward
                               autopair-backspace
                               kill-region))

(setq mc/cmds-to-run-once '(win-switch-down
                            eval-last-sexp
                            win-switch-exit
                            win-switch-exit-and-redo
                            win-switch-enter))

                            
                               