;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(add-semi-eol-and-goto-next-line-indented
                               repeat
                               c-electric-colon
                               delete-horizontal-space
                               dired-mark
                               ibuffer-mark-for-delete
                               downcase-region
                               smex
                               cperl-electric-terminator
                               upcase-region
                               c-electric-delete-forward
                               cperl-electric-brace
                               cperl-electric-lbrace
                               cperl-electric-backspace
                               cperl-electric-semi
                               yas-expand
                               beginning-of-buffer
                               autopair-skip-close-maybe
                               c-electric-slash
                               c-electric-semi&comma
                               c-electric-pound
                               c-electric-paren
                               comint-delchar-or-maybe-eof
                               c-electric-backspace
                               wgrep-finish-edit
                               autopair-skip-close-maybe
                               org-end-of-line
                               org-delete-char
                               org-beginning-of-line
                               autopair-insert-opening
                               js2-beginning-of-line
                               yas-expand
                               js2-end-of-line
                               autopair-insert-or-skip-quote
                               autopair-insert-opening
                               autopair-backspace
                               kill-region))

(setq mc/cmds-to-run-once '(handle-switch-frame
                            dired-next-line
                            dired-previous-line
                            wdired-finish-edit
                            sgml-delete-tag
                            win-switch-right
                            smart-compile
                            scroll-up-command
                            org-delete-backward-char
                            org-self-insert-command
                            win-switch-down
                            eval-last-sexp
                            win-switch-exit
                            win-switch-exit-and-redo
                            win-switch-enter))

                            
                               