;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(yas-expand
                               beginning-of-buffer
                               autopair-skip-close-maybe
                               autopair-insert-or-skip-quote
                               autopair-insert-opening
                               autopair-backspace
                               kill-region))

(setq mc/cmds-to-run-once '(win-switch-exit-and-redo
                            win-switch-enter))

                            
                               