language: emacs-lisp

env:
  matrix:
    - EMACS=emacs24

before_install:
  - git submodule --quiet update --init --recursive

install:
  - if [ "$EMACS" = "emacs24" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot &&
        sudo apt-get install -qq emacs-snapshot-el emacs-snapshot-gtk;
    fi

script:
   emacs -batch -L ./ -L ./elpa/ -L ./ert-tests/ -l ert -l ./ert-tests/dg-init-ert.el -f ert-run-tests-batch-and-exit

notifications:
  email: false

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
